version: "2"
services:
  db:
    image: postgres:9.4
    volumes_from:
      - dbdata
    environment:
      POSTGRES_DB: planeray
      POSTGRES_USER: planeray
      POSTGRES_PASSWORD: planeray
    ports:
      - "5432:5432"
  dbdata:
    image: postgres:9.4
    command: /bin/echo mysql Data container
  redis:
    image: redis
  dump1090:
    image: mlhamel/dump1090
    ports:
      - "8080:8080"
  server:
    build: .
    image: mlhamel/planeray
    command: bin/server
    volumes:
      - .:/planeray
    environment:
      RAILS_ENV: production
    links:
      - db
      - redis
      - dump1090
