development:
  adapter: sqlite3
  database: db/planeray_development.sqlite3

test:
  adapter: sqlite3
  database: db/planeray_test.sqlite3

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: planeray
  password: planeray
  database: planeray
