development:
  adapter: sqlite3
  database: db/planeray_development.sqlite3

test:
  adapter: sqlite3
  database: db/planeray_test.sqlite3

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['DB_ENV_MYSQL_ROOT_PASSWORD'] %>
  host: 'db'
  database: planeray
