# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee6f9182a41ab14a1f75028d124175ef7df693a4caddd7f3ba7c3465f681f1946f866a140c02ecfb31ed4313946595a58873c8b6f0d5c82e1ba57383e513f611

test:
  secret_key_base: 38b69bbc0c40dfb8a848a93182f24d2aff82f49af867c173beb26c8e2563a28811728d1cddaa156d5e2d7918ea76ee6823e83e64123fdb84d92bbb2f55882e66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
